### ISSUE TITLE
Thesis Model

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/thing#4]
- title
- abstract
- grad_date

relations:
- belongs_to :user
- has_one :right
- has_and_belongs_to_many :degrees
- has_and_belongs_to_many :departments
- has_and_belongs_to_many :advisors

**Comment by thatandromeda** [comment]
The relationships to `Right`, `Degree`, `Department`, and `Advisor` can't be created until those models exist, so I'm going to defer that part of this issue to the respective issues that create those models.
